name: "Backend CI/CD"

on:
  push:
    paths:
      - "backend/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Backend CI/CD
        run: |-
          echo "Hello World from Backend CI/CD"